### ISSUE TITLE
Unable to save this server, are the username and password correct?

### ISSUE THREAD

**Issue by XargonWan** [jasonmunro/cypht#727]
## 💬 Question
Whatever server I add, I got the following error: `Unable to save this server, are the username and password correct?`.
I tried google login, google IMAP, microsoft IMAP without any success.

I am running a test server with the default composer file:
```
version: '3'
services:
  db:
    image: mariadb:10
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=cypht_password
  cypht:
    image: sailfrog/cypht-docker:latest
    volumes:
      - ./cypht/users:/var/lib/hm3/users
    ports:
      - "8888:80"
    environment:
      - CYPHT_AUTH_USERNAME=admin
      - CYPHT_AUTH_PASSWORD=admin_password
      - CYPHT_DB_CONNECTION_TYPE=host
      - CYPHT_DB_HOST=db
      - CYPHT_DB_NAME=cypht
      - CYPHT_DB_USER=cypht
      - CYPHT_DB_PASS=cypht_password
      - CYPHT_SESSION_TYPE=DB
```

I don't know where the logs are located as with docker logs it prompt me the nginx logs.

Any help?
